### ISSUE TITLE
Collab?

### ISSUE THREAD

**Issue by aldanor** [stainless-steel/hdf5#1]
Hi! I've noticed you've started https://github.com/stainless-steel/hdf5-sys and https://github.com/stainless-steel/hdf5 repos and was wondering if you'd be interested in collaboration (I've been hacking on this lately -- https://github.com/aldanor/hdf5-rs) and there's a discussion with a few other folks going on in issue 1 of https://github.com/andreabedini/hdf5-rs.

Cheers :)

**Comment by IvanUkhov** [comment]
Hi! Yes, I’m very much interested in collaboration. I wrote a [package](https://github.com/ready-steady/hdf5) for Go, and I was planning to do the same for Rust. Thanks for letting me know!

Regards,
Ivan

**Comment by aldanor** [comment]
Great! I managed to implement most of the boring low-level stuff like handle management, recursive mutexes for thread safety and automatic error stack extraction, so it's more at a point now where one could hack on higher-level things. The elephant in the room being the multi-dimensional array backend, of course...

Cheers,
Ivan
