### ISSUE TITLE
Writing Vec's of structs?

### ISSUE THREAD

**Issue by SuperFluffy** [stainless-steel/hdf5#2]
I am playing around with your library because I want to dump some data stored in `Vec<Complex64>` vectors, where `Complex64 = num::complex::Complex<f64>`. This in turn is internally implemented as a simple `struct Complex<T> { re: T, im: T}`. It looks like I cannot directly write nor encode `Vec<Complex64>`:
- `pub fn write<T: IntoData>(&mut self, data: T, position: &[usize], size: &[usize]) -> Result<()>` wants a `T: IntoData`, which is not `impl`emented for `Complex<T>`;
- `fn encode<T: Encodable>(&self, name: &str, data: T) -> Result<()>` first creates a new `Encode`, so that I cannot simply iterate over my `Vec<Complex64`>.

Just for the hell of it I passed `encode()` my `Vec`, which resulted in `thread '<main>' panicked at 'called`Result::unwrap()`on an`Err`value: Error("cannot mix datatypes in arrays")', src/libcore/result.rs:731`.

Apart from unzipping each `Complex64` into two `f64` and then writing them separately, is there something else I can do?

Note: my temporary solution to this is doing something along the lines of:

```
let (xs, ys): (Vec<f64>, Vec<f64>) =
        complexvec
        .iter()
        .map(|&Complex64{ re: ref x, im: ref y }| (x,y))
        .unzip();

file.write("real", &xs);
file.write("imag", &ys);
```

Of course, it would be amazing if I didn't have to first create two additional structures.

**Comment by IvanUkhov** [comment]
Hi Richard,

Thanks for the feedback! That was a bug. Have a look at [this](https://github.com/stainless-steel/hdf5/blob/master/tests/encode.rs#L81) test, which is passing now. Apart from updating `hdf5`, make sure to get an updated version of `hdf5-sys` (just run `cargo update`).

I also would like to mention that this package is incomplete as the reading/decoding part is not implemented yet. If that is a problem for you, I recommend looking at [this](https://github.com/aldanor/hdf5-rs) alternative.

Regards,
Ivan

**Comment by SuperFluffy** [comment]
Hey Ivan!

Thanks for the fix; it works now. Your package is a lot more visible than [aldanor's](https://github.com/aldanor/hdf5-rs), as yours if published on [`crates.io`](https://crates.io). That's why I went with yours first. :)

Reading is not overly necessary for me right now, although it might be useful at some point. Maybe you could add a little todo/missing features to `README.md`?
