### ISSUE TITLE
reading functionality of hdf5?

### ISSUE THREAD

**Issue by andysureway-10x** [stainless-steel/hdf5#4]
Hello, thanks a lot for your efforts on sharing this crate on hdf5. I went through the src directory, and somehow I did not find a way to read hdf5 files. Not sure whether I miss something here. Thanks!

**Comment by IvanUkhov** [comment]
Currently the package is only capable of writing/encoding; the reading/decoding functionality is yet to be implemented. If you need reading, please have a look at the crates mentioned in #1. Thanks!
